@url_dev = http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: ee877f62e16ccc94c3f06cdf19c66647c5afd3cc2d7af95665a4bdc3696c68b9ef36f8689426d9d5cac1a634aaea6f839f3dc2bb2059e7753fdf1dba44a7dc89

{
    "name": "Shop TIPS",
    "email": "shopDevTipjs@gmail.com",
    "password": "abc123"
}

